"""System-level utilities for lmswitch."""

from lmswitch.system.io import (
    TTY,
    CONF_DIR,
    RUN_DIR,
    CONFIG_FILE,
    HOME,
    OPENCODE,
    OPENCODE_EXPORT,
    HERMES_CONFIG,
    GROK_CONFIG,
    SPARK_HOST,
    SYNC_OPENCODE,
    SYNC_HERMES,
    SYNC_GROK,
    DEFAULT_SYNC_TARGETS,
    SCRIPT_DIR,
    _c,
    _read_config,
    _models_dir,
    _human,
    _load_yaml,
    _parse_yaml_simple,
    _yaml_scalar,
    _family,
    _model_size_and_present,
    _get_sync_targets,
)
from lmswitch.system.checks import (
    _listening_ports,
    _docker_container,
    _is_running,
)
from lmswitch.system.memory import (
    _ram_line,
    _memory_check,
)

__all__ = [
    "TTY",
    "CONF_DIR",
    "RUN_DIR",
    "CONFIG_FILE",
    "HOME",
    "OPENCODE",
    "OPENCODE_EXPORT",
    "HERMES_CONFIG",
    "GROK_CONFIG",
    "SPARK_HOST",
    "SYNC_OPENCODE",
    "SYNC_HERMES",
    "SYNC_GROK",
    "DEFAULT_SYNC_TARGETS",
    "SCRIPT_DIR",
    "_c",
    "_read_config",
    "_models_dir",
    "_human",
    "_load_yaml",
    "_parse_yaml_simple",
    "_yaml_scalar",
    "_family",
    "_model_size_and_present",
    "_get_sync_targets",
    "_listening_ports",
    "_docker_container",
    "_is_running",
    "_ram_line",
    "_memory_check",
]
